"""crear tablas veterinarias y profesionales

Revision ID: 2df5ec4b8d80
Revises: fe5fc72af08c
Create Date: 2026-09-18 21:24:06.181581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2df5ec4b8d80'
down_revision: Union[str, None] = 'fe5fc72af08c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('veterinarias',
    sa.Column('id_veterinaria', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_comercial', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('correo_electronico', sa.String(length=100), nullable=True),
    sa.Column('horario_atencion', sa.String(length=100), nullable=True),
    sa.Column('latitud', sa.DECIMAL(precision=10, scale=8), nullable=True),
    sa.Column('longitud', sa.DECIMAL(precision=11, scale=8), nullable=True),
    sa.Column('calificacion_promedio', sa.DECIMAL(precision=3, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_veterinaria')
    )
    op.create_index(op.f('ix_veterinarias_id_veterinaria'), 'veterinarias', ['id_veterinaria'], unique=False)
    op.create_table('profesionales',
    sa.Column('id_profesional', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_veterinaria', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=100), nullable=False),
    sa.Column('especialidad', sa.String(length=50), nullable=True),
    sa.Column('numero_registro_profesional', sa.String(length=30), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('correo_electronico', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_veterinaria'], ['veterinarias.id_veterinaria'], ),
    sa.PrimaryKeyConstraint('id_profesional')
    )
    op.create_index(op.f('ix_profesionales_id_profesional'), 'profesionales', ['id_profesional'], unique=False)
    op.create_index(op.f('ix_profesionales_id_veterinaria'), 'profesionales', ['id_veterinaria'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profesionales_id_veterinaria'), table_name='profesionales')
    op.drop_index(op.f('ix_profesionales_id_profesional'), table_name='profesionales')
    op.drop_table('profesionales')
    op.drop_index(op.f('ix_veterinarias_id_veterinaria'), table_name='veterinarias')
    op.drop_table('veterinarias')
    # ### end Alembic commands ###