"""crear tabla citas_veterinarias

Revision ID: 9bfd81f0d1df
Revises: 2df5ec4b8d80
Create Date: 2026-09-18 21:36:27.788087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bfd81f0d1df'
down_revision: Union[str, None] = '2df5ec4b8d80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citas_veterinarias',
    sa.Column('id_cita', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_mascota', sa.Integer(), nullable=False),
    sa.Column('id_profesional', sa.Integer(), nullable=False),
    sa.Column('id_veterinaria', sa.Integer(), nullable=False),
    sa.Column('fecha_cita', sa.DateTime(timezone=True), nullable=False),
    sa.Column('motivo', sa.String(length=200), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_mascota'], ['mascotas.id_mascota'], ),
    sa.ForeignKeyConstraint(['id_profesional'], ['profesionales.id_profesional'], ),
    sa.ForeignKeyConstraint(['id_veterinaria'], ['veterinarias.id_veterinaria'], ),
    sa.PrimaryKeyConstraint('id_cita')
    )
    op.create_index(op.f('ix_citas_veterinarias_id_cita'), 'citas_veterinarias', ['id_cita'], unique=False)
    op.create_index(op.f('ix_citas_veterinarias_id_mascota'), 'citas_veterinarias', ['id_mascota'], unique=False)
    op.create_index(op.f('ix_citas_veterinarias_id_profesional'), 'citas_veterinarias', ['id_profesional'], unique=False)
    op.create_index(op.f('ix_citas_veterinarias_id_veterinaria'), 'citas_veterinarias', ['id_veterinaria'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_citas_veterinarias_id_veterinaria'), table_name='citas_veterinarias')
    op.drop_index(op.f('ix_citas_veterinarias_id_profesional'), table_name='citas_veterinarias')
    op.drop_index(op.f('ix_citas_veterinarias_id_mascota'), table_name='citas_veterinarias')
    op.drop_index(op.f('ix_citas_veterinarias_id_cita'), table_name='citas_veterinarias')
    op.drop_table('citas_veterinarias')
    # ### end Alembic commands ###