"""crear tabla mascotas

Revision ID: fe5fc72af08c
Revises: 7d8447a09fdd
Create Date: 2026-09-18 15:22:49.110998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe5fc72af08c'
down_revision: Union[str, None] = '7d8447a09fdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mascotas',
    sa.Column('id_mascota', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('especie', sa.String(length=30), nullable=False),
    sa.Column('raza', sa.String(length=50), nullable=True),
    sa.Column('sexo', sa.String(length=10), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('peso_kg', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('color_mascota', sa.String(length=30), nullable=True),
    sa.Column('numero_chip', sa.String(length=50), nullable=True),
    sa.Column('foto_url', sa.Text(), nullable=True),
    sa.Column('alergias', sa.Text(), nullable=True),
    sa.Column('condiciones_medicas', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_mascota'),
    sa.UniqueConstraint('numero_chip')
    )
    op.create_index(op.f('ix_mascotas_id_mascota'), 'mascotas', ['id_mascota'], unique=False)
    op.create_index(op.f('ix_mascotas_id_usuario'), 'mascotas', ['id_usuario'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mascotas_id_usuario'), table_name='mascotas')
    op.drop_index(op.f('ix_mascotas_id_mascota'), table_name='mascotas')
    op.drop_table('mascotas')
    # ### end Alembic commands ###